# Site settings
title: Xiong Feng's Personal Site
name: Xiong Feng's Personal Site
url: "http://xiongfeng.info"
email: xiongfeng_dev@qq.com
description: Xiong Feng's Personal Site | xiongfeng.info.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:
weibo_username: 简兮Eternity
duoshuo_username: jolin
baidushare_id: 89860593
baidutongji_id: d6cd03a958f8d0bc11d8a7c446181d2e
rss_url: "/rss.xml"
logo_image: "/images/logo.png"
# Build settings
highlighter: rouge
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: page/:num
# image
favicon: https://avatars0.githubusercontent.com/u/6395517?s=400&u=c270f88551f7a80b6c6606ece9c4c9384b029f98&v=4
